# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dc15dc18735b77602c0de5d43712c6c9c63bef54ac0a5eed8efb4c2bc9ca91a0bc74d94fde19a6c91b5b8605400db72d2fa411dc507faba1e618d0125bc41254

test:
  secret_key_base: 7f50e6f810e3a06c7a5f9429d36d468d9f4efe0398656631e9764b664eadc3bba4c06526797d4c0a9f0cfbf7844314446cfbb4379722d2eafaea6496ce1b45c1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
